name: flutter_icon_field
description: Componente Flutter inspirado no IconField do PrimeNG.
version: 1.0.0
homepage: https://github.com/andersonmatte/flutter_icon_field
repository: https://github.com/andersonmatte/flutter_icon_field
issue_tracker: https://github.com/andersonmatte/flutter_icon_field/issues
documentation: https://github.com/andersonmatte/flutter_icon_field#readme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/search.svg
